import Link from 'next/link';
import { ArrowRight, BookOpen } from 'lucide-react';

const phases=[
  ['Phase I','Enzyme screen','Classifies each protein as enzyme or non-enzyme using DPC + NMBroto features.'],
  ['Phase II','Mineralization screen','Tests qualifying enzymes for nitrogen mineralization-related function.'],
  ['Phase III','Enzyme class','Assigns qualifying proteins to one of ten enzyme classes.'],
  ['Phase IV','EC assignment','Uses the Phase III class to select the corresponding CKSAAP model and assign an EC label.'],
];

const enzymeClasses = [
  { name: 'Amidohydrolases', description: 'Hydrolyze non-peptide carbon–nitrogen bonds, including linear amides.', ec: ['3.5.1.1','3.5.1.2','3.5.1.4','3.5.1.5','3.5.1.11','3.5.1.28','3.5.1.68'] },
  { name: 'Aminopeptidases', description: 'Remove amino-acid residues from the amino terminus of peptides or proteins.', ec: ['3.4.11.-','3.4.11.1','3.4.11.2','3.4.11.4','3.4.11.5','3.4.11.6','3.4.11.9','3.4.11.10','3.4.11.18','3.4.11.19','3.4.11.24','Others'] },
  { name: 'Aspartic endopeptidases', description: 'Hydrolyze internal peptide bonds through an aspartate-dependent catalytic mechanism.', ec: ['3.4.23.-','3.4.23.12','3.4.23.21','3.4.23.24','3.4.23.36','3.4.23.43','3.4.23.51','Others'] },
  { name: 'Cysteine endopeptidases', description: 'Use a catalytic cysteine to hydrolyze internal peptide bonds.', ec: ['3.4.22.-','3.4.22.8','3.4.22.10','3.4.22.37','3.4.22.40','3.4.22.49','3.4.22.68','3.4.22.70','3.4.22.71','Others'] },
  { name: 'Dipeptidases', description: 'Hydrolyze dipeptides into their component amino acids.', ec: ['3.4.13.-','3.4.13.9','3.4.13.19','3.4.13.20','3.4.13.21','3.4.13.22','Others'] },
  { name: 'Dipeptidyl-peptidases', description: 'Release a dipeptide from the amino terminus of a peptide or protein.', ec: ['3.4.14.-','3.4.14.1','3.4.14.5','3.4.14.10','3.4.14.11','3.4.14.12','Others'] },
  { name: 'Metalloendopeptidases', description: 'Use a metal ion to catalyze hydrolysis of internal peptide bonds.', ec: ['3.4.24.-','3.4.24.3','3.4.24.13','3.4.24.39','3.4.24.40','3.4.24.55','3.4.24.64','3.4.24.75','3.4.24.84','Others'] },
  { name: 'Metallopeptidases', description: 'Metal-dependent exopeptidases represented by the EC 3.4.17 group.', ec: ['3.4.17.-','3.4.17.11','3.4.17.13','3.4.17.14','3.4.17.18','3.4.17.19','3.4.17.21','3.4.17.24','Others'] },
  { name: 'Omega peptidases', description: 'Hydrolyze specialized terminal or isopeptide linkages in the EC 3.4.19 group.', ec: ['3.4.19.-','3.4.19.1','3.4.19.2','3.4.19.9','3.4.19.11','3.4.19.12','Others'] },
  { name: 'Serine endopeptidases', description: 'Use a catalytic serine to hydrolyze internal peptide bonds.', ec: ['3.4.21.-','3.4.21.53','3.4.21.62','3.4.21.88','3.4.21.89','3.4.21.92','3.4.21.102','3.4.21.105','3.4.21.107','Others'] },
];

export default function Help(){return <div className="py-5 sm:py-8">
  <header className="border-b border-[var(--line)] pb-8"><p className="eyebrow flex items-center gap-2"><BookOpen className="h-4 w-4"/> User guide</p><h1 className="mt-3 font-display text-4xl font-semibold">MINpred methods and output guide</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Prepare sequence data, choose a prediction phase, and interpret the enzyme-class and EC outputs returned by MINpred.</p></header>
  <div className="mt-8 grid gap-8 lg:grid-cols-[220px_minmax(0,1fr)]"><aside><div className="sticky top-24"><p className="eyebrow">On this page</p><nav className="mt-4 border-l border-[var(--line)] text-sm" aria-label="Help sections">{[['input','Input sequences'],['levels','Prediction phases'],['routing','Phase IV routing'],['classes','Classes and EC labels'],['results','Results and downloads'],['privacy','Privacy']].map(([id,label])=><a key={id} href={`#${id}`} className="block border-l-2 border-transparent px-4 py-2 text-[var(--muted)] transition hover:border-[var(--mineral)] hover:text-[var(--ink)]">{label}</a>)}</nav><div className="mt-7 border-t border-[var(--line)] pt-5"><p className="text-xs leading-5 text-[var(--muted)]">Paste or retrieve FASTA, select the last phase you need, then keep the private result link.</p><Link href="/prediction" className="btn-primary mt-4 w-full">Open prediction <ArrowRight className="h-4 w-4"/></Link></div></div></aside>
  <main className="surface overflow-hidden">
    <section id="input" className="scroll-mt-24 border-b border-[var(--line)] p-6 sm:p-8"><p className="eyebrow">01 · Input sequences</p><h2 className="mt-2 font-display text-3xl font-semibold">Protein and nucleotide FASTA</h2><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Every record needs a unique header. Protein input accepts the 20 standard amino acids plus X. Nucleotide input accepts A, C, G, T, U, and N; TransDecoder.LongOrfs generates <code className="rounded bg-[var(--mist)] px-1.5 py-0.5">translated_proteins.fasta</code> before prediction. Accession retrieval is available for proteins through UniProtKB and NCBI Protein.</p>
      <div className="mt-6 grid border-y border-[var(--line)] text-xs sm:grid-cols-3 sm:divide-x sm:divide-[var(--line)]"><div className="py-4 sm:pr-4"><strong className="block text-[var(--ink)]">Paste</strong><span className="mt-1 block text-[var(--muted)]">Enter one or more FASTA records.</span></div><div className="py-4 sm:px-4"><strong className="block text-[var(--ink)]">Upload</strong><span className="mt-1 block text-[var(--muted)]">Use FASTA, FA, FAA, or text files.</span></div><div className="py-4 sm:pl-4"><strong className="block text-[var(--ink)]">Accession</strong><span className="mt-1 block text-[var(--muted)]">Retrieve protein sequences by identifier.</span></div></div>
    </section>
    <section id="levels" className="scroll-mt-24 border-b border-[var(--line)] p-6 sm:p-8"><p className="eyebrow">02 · Prediction phases</p><h2 className="mt-2 font-display text-3xl font-semibold">Choose the last result you need</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Each phase includes all preceding phases.</p><div className="mt-6 divide-y divide-[var(--line)] border-y border-[var(--line)]">{phases.map(([phase,title,text],index)=><article key={phase} className="grid gap-2 py-5 sm:grid-cols-[48px_190px_1fr]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--forest)] text-xs font-bold text-white">{index+1}</span><div><p className="text-[11px] font-bold uppercase tracking-wider text-[var(--mineral)]">{phase}</p><h3 className="mt-1 font-semibold">{title}</h3></div><p className="text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div></section>
    <section id="routing" className="scroll-mt-24 border-b border-[var(--line)] p-6 sm:p-8"><p className="eyebrow">03 · Phase IV routing</p><h2 className="mt-2 font-display text-3xl font-semibold">Automatic or class-restricted</h2><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="border-t-2 border-[var(--forest)] pt-4"><h3 className="font-semibold">Determine automatically</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">MINpred uses each sequence’s Phase III prediction to select the matching Phase IV EC model.</p></div><div className="border-t-2 border-[var(--mineral)] pt-4"><h3 className="font-semibold">Use a specific class</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Only sequences assigned to the selected class in Phase III continue to that Phase IV model.</p></div></div></section>
    <section id="classes" className="scroll-mt-24 border-b border-[var(--line)]"><header className="p-6 sm:p-8"><p className="eyebrow">04 · Class and EC reference</p><h2 className="mt-2 font-display text-3xl font-semibold">Ten enzyme classes and 69 named EC labels</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Phase III assigns one of the ten classes below. Phase IV predicts among the labels available for the corresponding class-specific model.</p></header><div className="divide-y divide-[var(--line)] border-t border-[var(--line)]">{enzymeClasses.map((group,index)=><article key={group.name} className="grid gap-4 px-6 py-6 sm:px-8 xl:grid-cols-[38px_220px_1fr]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--mist)] text-xs font-black text-[var(--forest)]">{String(index+1).padStart(2,'0')}</span><div><h3 className="font-semibold">{group.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{group.description}</p></div><div className="flex flex-wrap content-start gap-1.5">{group.ec.map(label=><code key={label} className={`rounded-lg border px-2 py-1 text-[11px] ${label==='Others'?'border-dashed border-[#b9b5ab] text-[var(--muted)]':'border-[var(--line)] bg-[var(--canvas)] text-[var(--forest-dark)]'}`}>{label}</code>)}</div></article>)}</div><footer className="border-t border-[var(--line)] bg-[var(--mist)] px-6 py-6 text-xs leading-5 text-[var(--muted)] sm:px-8"><p><strong className="text-[var(--ink)]">Reading an EC label:</strong> the four positions describe progressively narrower enzyme categories. For example, <code>3.4.11.1</code> belongs to hydrolases (3), acts on peptide bonds (3.4), is an aminopeptidase (3.4.11), and identifies a specific entry.</p><p className="mt-2"><code>3.4.11.-</code> denotes the broader subgroup without a specific fourth-level entry. <code>Others</code> is the combined output for represented records outside the named labels. Check current nomenclature in the <a className="font-semibold underline" href="https://www.enzyme-database.org/" target="_blank" rel="noreferrer">IUBMB Enzyme Nomenclature database</a>.</p></footer></section>
    <section id="results" className="scroll-mt-24 border-b border-[var(--line)] p-6 sm:p-8"><p className="eyebrow">05 · Results and downloads</p><h2 className="mt-2 font-display text-3xl font-semibold">Inspect, export, or continue locally</h2><div className="mt-6 grid gap-7 md:grid-cols-[1fr_1.15fr]"><div><h3 className="font-semibold">Web results</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Download tables as TSV, CSV, or JSON. EC predictions link to NCBI, UniProt, BRENDA, KEGG, and JGI. Structure tools are available when their services are configured.</p></div><div><h3 className="font-semibold">Standalone examples</h3><pre className="mt-3 overflow-x-auto rounded-xl bg-[var(--forest-dark)] p-4 text-[11px] leading-6 text-white">{`minpred -i proteins.fasta -od results -l Phase3\nminpred -i proteins.fasta -od results -l Phase4\nminpred -i transcripts.fasta --sequence-type nucleotide -od results -l Phase4`}</pre></div></div></section>
    <section id="privacy" className="scroll-mt-24 p-6 sm:p-8"><p className="eyebrow">06 · Privacy</p><h2 className="mt-2 font-display text-3xl font-semibold">Keep the complete result link private</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Anyone with the full link can open the result. Submitted sequences and results are deleted after 30 days by default.</p></section>
  </main></div>
</div>}
