import Link from 'next/link';
import { BookOpen, FileText, Layers3, LockKeyhole, Server } from 'lucide-react';

const phases=[
  ['Phase I','Enzyme screen','Classifies each protein as enzyme or non-enzyme using DPC + NMBroto features.'],
  ['Phase II','Mineralization screen','Tests qualifying enzymes for nitrogen mineralization-related function.'],
  ['Phase III','Enzyme class','Assigns qualifying proteins to one of ten enzyme classes.'],
  ['Phase IV','EC assignment','Uses the Phase III class to select the corresponding CKSAAP model and assign an EC label.'],
];

const enzymeClasses = [
  { name: 'Amidohydrolases', description: 'Hydrolyze non-peptide carbon–nitrogen bonds, including linear amides.', ec: ['3.5.1.1','3.5.1.2','3.5.1.4','3.5.1.5','3.5.1.11','3.5.1.28','3.5.1.68'] },
  { name: 'Aminopeptidases', description: 'Remove amino-acid residues from the amino terminus of peptides or proteins.', ec: ['3.4.11.-','3.4.11.1','3.4.11.2','3.4.11.4','3.4.11.5','3.4.11.6','3.4.11.9','3.4.11.10','3.4.11.18','3.4.11.19','3.4.11.24','Others'] },
  { name: 'Aspartic endopeptidases', description: 'Hydrolyze internal peptide bonds through an aspartate-dependent catalytic mechanism.', ec: ['3.4.23.-','3.4.23.12','3.4.23.21','3.4.23.24','3.4.23.36','3.4.23.43','3.4.23.51','Others'] },
  { name: 'Cysteine endopeptidases', description: 'Use a catalytic cysteine to hydrolyze internal peptide bonds.', ec: ['3.4.22.-','3.4.22.8','3.4.22.10','3.4.22.37','3.4.22.40','3.4.22.49','3.4.22.68','3.4.22.70','3.4.22.71','Others'] },
  { name: 'Dipeptidases', description: 'Hydrolyze dipeptides into their component amino acids.', ec: ['3.4.13.-','3.4.13.9','3.4.13.19','3.4.13.20','3.4.13.21','3.4.13.22','Others'] },
  { name: 'Dipeptidyl-peptidases', description: 'Release a dipeptide from the amino terminus of a peptide or protein.', ec: ['3.4.14.-','3.4.14.1','3.4.14.5','3.4.14.10','3.4.14.11','3.4.14.12','Others'] },
  { name: 'Metalloendopeptidases', description: 'Use a metal ion to catalyze hydrolysis of internal peptide bonds.', ec: ['3.4.24.-','3.4.24.3','3.4.24.13','3.4.24.39','3.4.24.40','3.4.24.55','3.4.24.64','3.4.24.75','3.4.24.84','Others'] },
  { name: 'Metallopeptidases', description: 'Metal-dependent exopeptidases represented by the EC 3.4.17 group.', ec: ['3.4.17.-','3.4.17.11','3.4.17.13','3.4.17.14','3.4.17.18','3.4.17.19','3.4.17.21','3.4.17.24','Others'] },
  { name: 'Omega peptidases', description: 'Hydrolyze specialized terminal or isopeptide linkages in the EC 3.4.19 group.', ec: ['3.4.19.-','3.4.19.1','3.4.19.2','3.4.19.9','3.4.19.11','3.4.19.12','Others'] },
  { name: 'Serine endopeptidases', description: 'Use a catalytic serine to hydrolyze internal peptide bonds.', ec: ['3.4.21.-','3.4.21.53','3.4.21.62','3.4.21.88','3.4.21.89','3.4.21.92','3.4.21.102','3.4.21.105','3.4.21.107','Others'] },
];

export default function Help(){return <div className="space-y-8 py-5 sm:py-8">
  <header className="border-y border-[var(--line)] bg-[var(--paper)] px-6 py-9 sm:px-9"><p className="eyebrow flex items-center gap-2"><BookOpen className="h-4 w-4"/> User guide</p><h1 className="mt-3 font-display text-4xl font-semibold">Using MINpred</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Prepare FASTA, choose the prediction depth, and keep the private results link.</p></header>
  <div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="surface h-fit p-5"><p className="eyebrow">Quick start</p><ol className="mt-4 space-y-4 text-sm text-[var(--muted)]"><li className="flex gap-3"><FileText className="h-4 w-4 text-[var(--forest)]"/>Paste, upload, or retrieve FASTA.</li><li className="flex gap-3"><Layers3 className="h-4 w-4 text-[var(--forest)]"/>Select Phase I, II, III, or IV.</li><li className="flex gap-3"><Server className="h-4 w-4 text-[var(--forest)]"/>Start the prediction and wait for processing.</li><li className="flex gap-3"><LockKeyhole className="h-4 w-4 text-[var(--forest)]"/>Save the private result URL.</li></ol><Link href="/prediction" className="btn-primary mt-6 w-full">Open prediction</Link></aside>
  <main className="space-y-4"><section className="surface p-6"><p className="eyebrow">Input rules</p><h2 className="mt-2 font-display text-2xl font-semibold">Protein and nucleotide FASTA</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Every record needs a unique header. Protein input accepts the 20 standard amino acids plus X. Nucleotide input accepts A, C, G, T, U, and N; TransDecoder.LongOrfs generates a stable <code>translated_proteins.fasta</code> file before MINpred runs. Accession retrieval is protein-only.</p></section>
  <section className="surface p-6"><p className="eyebrow">Prediction levels</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{phases.map(([phase,title,text])=><article key={phase} className="rounded-xl border border-[var(--line)] p-4"><p className="text-xs font-black text-[var(--mineral)]">{phase}</p><h3 className="mt-1 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{text}</p></article>)}</div></section>
  <section className="surface p-6"><p className="eyebrow">Phase IV routing</p><h2 className="mt-2 font-display text-2xl font-semibold">Automatic or class-restricted prediction</h2><div className="mt-4 divide-y divide-[var(--line)] border-y border-[var(--line)] text-sm"><div className="grid gap-1 py-4 sm:grid-cols-[170px_1fr]"><strong>Determine automatically</strong><p className="text-[var(--muted)]">MINpred uses each sequence’s Phase III prediction to select the matching Phase IV EC model.</p></div><div className="grid gap-1 py-4 sm:grid-cols-[170px_1fr]"><strong>Use a specific class</strong><p className="text-[var(--muted)]">MINpred applies only the selected class route. A sequence must still be assigned to that class in Phase III to receive a Phase IV prediction.</p></div></div></section>
  <section className="surface p-6"><p className="eyebrow">Result tools</p><h2 className="mt-2 font-display text-2xl font-semibold">Inspect and export each phase</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Result tables can be downloaded as TSV, CSV, or JSON. EC predictions link to NCBI, UniProt, BRENDA, KEGG, and JGI. Secondary- and tertiary-structure tools are available for result sequences when the corresponding services are configured.</p></section>
  <section className="surface p-6"><h2 className="font-display text-2xl font-semibold">Standalone examples</h2><pre className="mt-4 overflow-x-auto bg-[var(--forest-dark)] p-5 text-xs leading-6 text-white">{`minpred -i proteins.fasta -od results -l Phase3\nminpred -i proteins.fasta -od results -l Phase4\nminpred -i transcripts.fasta --sequence-type nucleotide -od results -l Phase4`}</pre><p className="mt-3 text-sm text-[var(--muted)]">Phase IV routes each Phase III prediction to its matching EC model. Nucleotide mode requires TransDecoder.LongOrfs.</p></section>
  <section className="surface p-6"><p className="eyebrow">Privacy and retention</p><h2 className="mt-2 font-display text-2xl font-semibold">Keep the complete result link private</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Anyone with the full link can open the result. Submitted sequences and results are deleted after 30 days by default.</p></section></main></div>
  <section className="surface overflow-hidden"><header className="border-b border-[var(--line)] px-6 py-7 sm:px-8"><p className="eyebrow">Phase III and Phase IV reference</p><h2 className="mt-2 font-display text-3xl font-semibold">Ten enzyme classes and their EC outputs</h2><p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--muted)]">Phase III assigns one of the ten classes below. Phase IV then predicts among the EC labels available for that class-specific model. Across all classes, MINpred contains 69 named, fully specified EC labels.</p></header><div className="divide-y divide-[var(--line)]">{enzymeClasses.map((group,index)=><article key={group.name} className="grid gap-4 px-6 py-6 sm:px-8 lg:grid-cols-[42px_250px_1fr]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--mist)] text-xs font-black text-[var(--forest)]">{String(index+1).padStart(2,'0')}</span><div><h3 className="font-semibold text-[var(--forest-dark)]">{group.name}</h3><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{group.description}</p></div><div className="flex flex-wrap content-start gap-1.5">{group.ec.map(label=><code key={label} className={`rounded-lg border px-2 py-1 text-[11px] ${label==='Others'?'border-dashed border-[#b9b5ab] text-[var(--muted)]':'border-[var(--line)] bg-[var(--canvas)] text-[var(--forest-dark)]'}`}>{label}</code>)}</div></article>)}</div><footer className="border-t border-[var(--line)] bg-[var(--mist)] px-6 py-5 text-xs leading-5 text-[var(--muted)] sm:px-8"><p><strong className="text-[var(--ink)]">How to read an EC label:</strong> the four positions describe progressively narrower enzyme categories. For example, <code>3.4.11.1</code> belongs to hydrolases (3), acts on peptide bonds (3.4), is an aminopeptidase (3.4.11), and identifies a specific enzyme entry.</p><p className="mt-2"><code>3.4.11.-</code> means the model supports the broader subgroup but not a specific fourth-level entry. <code>Others</code> is the class model’s combined output for represented records outside its named labels. EC nomenclature can be checked through the <a className="font-semibold underline" href="https://www.enzyme-database.org/" target="_blank" rel="noreferrer">IUBMB Enzyme Nomenclature database</a>.</p></footer></section>
</div>}
