import Link from 'next/link';
import { BookOpen, FileText, Layers3, LockKeyhole, Server } from 'lucide-react';

const phases=[
  ['Phase I','Enzyme screen','Classifies each protein as enzyme or non-enzyme using DPC + NMBroto features.'],
  ['Phase II','Mineralization screen','Tests qualifying enzymes for nitrogen mineralization-related function.'],
  ['Phase III','Enzyme class','Assigns qualifying proteins to one of ten enzyme classes.'],
  ['Phase IV','EC assignment','Uses the Phase III class to select the corresponding CKSAAP model and assign an EC label.'],
];

export default function Help(){return <div className="space-y-8 py-5 sm:py-8">
  <header className="border-y border-[var(--line)] bg-[var(--paper)] px-6 py-9 sm:px-9"><p className="eyebrow flex items-center gap-2"><BookOpen className="h-4 w-4"/> User guide</p><h1 className="mt-3 font-display text-4xl font-semibold">Using MINpred</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Prepare FASTA, choose the prediction depth, and keep the private results link.</p></header>
  <div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="surface h-fit p-5"><p className="eyebrow">Quick start</p><ol className="mt-4 space-y-4 text-sm text-[var(--muted)]"><li className="flex gap-3"><FileText className="h-4 w-4 text-[var(--forest)]"/>Paste, upload, or retrieve FASTA.</li><li className="flex gap-3"><Layers3 className="h-4 w-4 text-[var(--forest)]"/>Select Phase I, II, III, or IV.</li><li className="flex gap-3"><Server className="h-4 w-4 text-[var(--forest)]"/>Submit to the configured SLURM executor.</li><li className="flex gap-3"><LockKeyhole className="h-4 w-4 text-[var(--forest)]"/>Save the private result URL.</li></ol><Link href="/prediction" className="btn-primary mt-6 w-full">Open prediction</Link></aside>
  <main className="space-y-4"><section className="surface p-6"><p className="eyebrow">Input rules</p><h2 className="mt-2 font-display text-2xl font-semibold">Protein and nucleotide FASTA</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Every record needs a unique header. Protein input accepts the 20 standard amino acids plus X. Nucleotide input accepts A, C, G, T, U, and N; TransDecoder.LongOrfs generates a stable <code>translated_proteins.fasta</code> file before MINpred runs. Accession retrieval is protein-only.</p></section>
  <section className="surface p-6"><p className="eyebrow">Prediction levels</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{phases.map(([phase,title,text])=><article key={phase} className="rounded-xl border border-[var(--line)] p-4"><p className="text-xs font-black text-[var(--mineral)]">{phase}</p><h3 className="mt-1 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{text}</p></article>)}</div></section>
  <section className="surface p-6"><p className="eyebrow">Result tools</p><h2 className="mt-2 font-display text-2xl font-semibold">Inspect and export each phase</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Result tables can be downloaded as TSV, CSV, or JSON. EC predictions link to NCBI, UniProt, BRENDA, KEGG, and JGI. Secondary- and tertiary-structure tools are available for result sequences when the corresponding services are configured.</p></section>
  <section className="surface p-6"><h2 className="font-display text-2xl font-semibold">Standalone examples</h2><pre className="mt-4 overflow-x-auto bg-[var(--forest-dark)] p-5 text-xs leading-6 text-white">{`minpred -i proteins.fasta -od results -l Phase3\nminpred -i proteins.fasta -od results -l Phase4\nminpred -i transcripts.fasta --sequence-type nucleotide -od results -l Phase4`}</pre><p className="mt-3 text-sm text-[var(--muted)]">Phase IV routes each Phase III prediction to its matching EC model. Nucleotide mode requires TransDecoder.LongOrfs.</p></section>
  <section className="surface p-6"><p className="eyebrow">Privacy and retention</p><h2 className="mt-2 font-display text-2xl font-semibold">Keep the complete result link private</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Anyone with the full link can open the result. Submitted sequences and results are deleted after 30 days by default.</p></section></main></div>
</div>}
